### ISSUE TITLE
システムスペックを書く

### ISSUE THREAD

**Issue by Saki-htr** [Saki-htr/fjord-choice#128]
## todo
- [x] sessions
- [x] retirements
- [x] home

**Comment by Saki-htr** [comment]
- bootcampのvcr参考：[新規ユーザー登録時にメンターにメール通知およびサイト内通知するようにした by SatoshiHaramura · Pull Request \#5227 · fjordllc/bootcamp](https://github.com/fjordllc/bootcamp/pull/5227/files)

**Comment by Saki-htr** [comment]
## 必要なテスト洗い出し
- [ ] ボタンクリックしたら、GitHub認証画面が出てログインできる。→ボタンが「メンバーから外れる」&ログインしてるユーザーのimage_urlとnameが表示される
- [ ] 登録ユーザーが1人以上いたら、tableにuserのimage_url / name / ポイント / プルリク / 合計 が表示される。リンクを持ってることもテスト。
- [ ] レビュー依頼されてるPR数が0件の場合「-」が表示 & 合計が「0」
- 「メンバーから外れる」ボタンをクリックしたら
- [ ] 登録ユーザーが0人の場合、「まだ誰も登録していません」と表示される
- [ ] 「このサービスについて」の？マークをクリックしたらモーダルが表示
- [ ] 「ポイント」の？マークにhoverしたら説明表示
- [ ] 「レビュー依頼されているプルリクエスト」の？マークにhoverしたら説明表示

**Comment by Saki-htr** [comment]
システムテストの構成は、卒業生の方のサービスを見ていると、主に以下の2パターンでファイル分けしている。
- 機能別(認証機能など)
- ページ別

**Comment by Saki-htr** [comment]
#164 で対応したのでcloseします。
