### ISSUE TITLE
色を付ける

### ISSUE THREAD

**Issue by Saki-htr** [Saki-htr/fjord-choice#33]
### todo
- [x] 背景色
- [x] ボタン:特に色はつけない方が見やすいと判断し、そのままにした。
- [x] モーダル
- [x] アイコンにホバーした時画像を暗くする
- [x] サービスの説明?マークのホバー時の色
- [x] ユーザー名とプルリクのタイトルの色：デフォルトだと、通常時に色が付いていてホバー時に黒字になるが、色がついているとテーブルの表として見にくいので、逆にした。
- [x] プログレスバーの色:bulmaの`primary`そのまま。
- [x] GitHubとTwitterのアイコン:そんなに目立たせたいアイコンではないので、通常時は黒、ホバー時色付きにした。
  - [x] ホバー時 
- [x] フォントを決める。canvaで作ったロゴのフォントは`Noto Sans Regular`

**Comment by Saki-htr** [comment]
完了してマージしたのでcloseします。
